INSERT INTO diplome VALUES (DEFAULT, 'BTS', 2);
INSERT INTO diplome VALUES (DEFAULT, 'Licence', 3);
INSERT INTO diplome VALUES (DEFAULT, 'Master 1', 4);
INSERT INTO diplome VALUES (DEFAULT, 'Master 2', 5);
INSERT INTO diplome VALUES (DEFAULT, 'Docteur', 8);